"""
postman_exporter.py — Postman Collection Generator

Converts endpoint configurations into a Postman-compatible
Collection v2.1 JSON file that can be imported directly into
Postman for manual or automated testing.

Author: Sandrine Uwineza
"""

import json
import uuid
from datetime import datetime, timezone
from typing import Optional


def _make_postman_item(endpoint: dict, base_url: str, default_headers: dict) -> dict:
    """Convert a single endpoint config into a Postman item."""
    method = endpoint.get("method", "GET").upper()
    path   = endpoint.get("path",   "/")
    name   = endpoint.get("name",   "Unnamed Request")
    body   = endpoint.get("body")
    tags   = endpoint.get("tags",   [])

    # Parse URL
    url_str = base_url.rstrip("/") + path
    parsed  = url_str.replace("https://", "").replace("http://", "")
    parts   = parsed.split("/", 1)
    host    = parts[0]
    path_parts = parts[1].split("/") if len(parts) > 1 else []

    # Build headers
    merged_headers = {**default_headers, **endpoint.get("headers", {})}
    header_list = [
        {"key": k, "value": v, "type": "text"}
        for k, v in merged_headers.items()
    ]

    # Build request body
    request_body = None
    if body:
        request_body = {
            "mode": "raw",
            "raw": json.dumps(body, indent=2),
            "options": {
                "raw": {"language": "json"}
            }
        }

    # Build tests script
    expected_status = endpoint.get("expected_status", 200)
    threshold_ms    = endpoint.get("latency_threshold_ms", 2000)
    expected_fields = endpoint.get("expected_fields", [])

    test_scripts = [
        f'pm.test("Status code is {expected_status}", function () {{',
        f'    pm.response.to.have.status({expected_status});',
        f'}});',
        f'',
        f'pm.test("Response time is under {threshold_ms}ms", function () {{',
        f'    pm.expect(pm.response.responseTime).to.be.below({threshold_ms});',
        f'}});',
        f'',
        f'pm.test("Response has valid JSON body", function () {{',
        f'    pm.response.to.be.json;',
        f'}});',
    ]

    for field in expected_fields:
        test_scripts += [
            f'',
            f'pm.test("Response has field: {field}", function () {{',
            f'    var jsonData = pm.response.json();',
            f'    pm.expect(jsonData).to.have.property("{field}");',
            f'}});',
        ]

    return {
        "name": name,
        "event": [
            {
                "listen": "test",
                "script": {
                    "exec": test_scripts,
                    "type": "text/javascript"
                }
            }
        ],
        "request": {
            "method": method,
            "header": header_list,
            "body":   request_body,
            "url": {
                "raw":  url_str,
                "protocol": "https" if url_str.startswith("https") else "http",
                "host": [host],
                "path": path_parts,
            },
            "description": endpoint.get("description", "")
        },
        "response": [],
        "_postman_id": str(uuid.uuid4()),
    }


def export_postman_collection(config: dict) -> dict:
    """
    Generate a complete Postman Collection v2.1 from an endpoint config.

    Args:
        config: Parsed endpoints.json configuration

    Returns:
        Postman Collection dict (ready to dump as JSON)
    """
    name            = config.get("name",            "REST API Testing Framework")
    description     = config.get("description",     "Auto-generated by REST API Testing Framework")
    version         = config.get("version",         "1.0.0")
    author          = config.get("author",          "Sandrine Uwineza")
    base_url        = config.get("base_url",        "https://httpbin.org")
    default_headers = config.get("default_headers", {})
    endpoints       = config.get("endpoints",       [])

    # Group endpoints by tag for folder organisation
    tagged_groups: dict[str, list] = {}
    untagged: list = []

    for endpoint in endpoints:
        tags = endpoint.get("tags", [])
        if tags:
            primary_tag = tags[0]
            if primary_tag not in tagged_groups:
                tagged_groups[primary_tag] = []
            tagged_groups[primary_tag].append(endpoint)
        else:
            untagged.append(endpoint)

    # Build collection items (folders)
    items = []

    for tag, tag_endpoints in tagged_groups.items():
        folder = {
            "name": tag.upper(),
            "item": [
                _make_postman_item(ep, base_url, default_headers)
                for ep in tag_endpoints
            ],
            "_postman_id": str(uuid.uuid4()),
        }
        items.append(folder)

    # Add untagged endpoints at root
    for endpoint in untagged:
        items.append(_make_postman_item(endpoint, base_url, default_headers))

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    collection = {
        "info": {
            "_postman_id": str(uuid.uuid4()),
            "name":        name,
            "description": (
                f"{description}\n\n"
                f"Author: {author}\n"
                f"Version: {version}\n"
                f"Base URL: {base_url}\n"
                f"Generated: {generated_at}\n"
                f"Tool: REST API Testing Framework — "
                f"github.com/sandrineuwineza/rest-api-testing-framework"
            ),
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        "variable": [
            {
                "key":   "base_url",
                "value": base_url,
                "type":  "string"
            }
        ],
        "item": items,
    }

    return collection


def export_to_file(config: dict, output_path: str) -> str:
    """Export Postman collection to a JSON file."""
    collection = export_postman_collection(config)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(collection, f, indent=2)
    return output_path
