"""
report_generator.py — Test Report Generator

Generates professional Markdown and JSON reports from test suite results.
Reports can be used as incident documentation or CI/CD artifacts.

Author: Sandrine Uwineza
"""

import json
from datetime import datetime, timezone
from runner import TestSuiteResult, EndpointResult


def generate_markdown_report(
    suite:   TestSuiteResult,
    analyst: str = "Sandrine Uwineza",
) -> str:
    """Generate a professional Markdown test report."""

    now      = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pass_icon = "✅" if suite.pass_rate >= 80 else "⚠️" if suite.pass_rate >= 50 else "❌"

    lines = [
        "# API Test Report",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| **Suite** | {suite.name} |",
        f"| **Base URL** | `{suite.base_url}` |",
        f"| **Generated** | {now} |",
        f"| **Analyst** | {analyst} |",
        f"| **Duration** | {suite.duration_ms:.0f} ms |",
        f"| **Pass Rate** | {pass_icon} {suite.pass_rate}% ({suite.passed}/{suite.total}) |",
        f"| **Avg Latency** | {suite.avg_latency_ms} ms |" if suite.avg_latency_ms else "",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"| Status | Count |",
        f"|---|---|",
        f"| ✅ Passed | {suite.passed} |",
        f"| ❌ Failed | {suite.failed} |",
        f"| 🔌 Errors | {suite.errors} |",
        f"| **Total** | **{suite.total}** |",
        "",
        "---",
        "",
        "## Endpoint Results",
        "",
    ]

    for result in suite.results:
        icon   = "✅" if result.passed else ("🔌" if result.error else "❌")
        method = f"`{result.method}`"
        lines.append(f"### {icon} {result.endpoint_name}")
        lines.append("")
        lines.append(f"| Field | Value |")
        lines.append(f"|---|---|")
        lines.append(f"| Method | {method} |")
        lines.append(f"| URL | `{result.url}` |")
        lines.append(f"| Result | {result.summary} |")
        lines.append(f"| Tags | {', '.join(result.tags) if result.tags else '—'} |")
        lines.append("")

        if result.error:
            lines.append(f"> ❌ **Connection Error:** {result.error}")
            lines.append("")
            continue

        # Status check
        if result.status:
            icon_s = "✅" if result.status.passed else "❌"
            lines.append(f"**Status Check:** {icon_s} {result.status.message}")
            lines.append("")

        # Schema check
        if result.schema:
            icon_s = "✅" if result.schema.passed else "❌"
            lines.append(f"**Schema Check:** {icon_s} {result.schema.message}")
            if result.schema.errors:
                for err in result.schema.errors:
                    lines.append(f"  - {err}")
            lines.append("")

        # Latency check
        if result.latency:
            icon_l = "✅" if result.latency.passed else "❌"
            lines.append(f"**Latency Check:** {icon_l} {result.latency.message}")
            lines.append("")

        # Payload check
        if result.payload:
            icon_p = "✅" if result.payload.passed else "❌"
            lines.append(f"**Payload Check:** {icon_p} {result.payload.message}")
            if result.payload.issues:
                for issue in result.payload.issues:
                    lines.append(f"  - ⚠️ {issue}")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Footer
    lines += [
        f"*Report generated by [REST API Testing Framework]"
        f"(https://github.com/sandrineuwineza/rest-api-testing-framework) "
        f"· {now}*",
        f"",
        f"*Analyst: {analyst} — Technical Support Engineer · CCNA Certified*",
    ]

    return "\n".join(line for line in lines if line is not None)


def generate_json_report(suite: TestSuiteResult) -> dict:
    """Generate a structured JSON report for API or CI/CD consumption."""
    return {
        "suite": {
            "name":         suite.name,
            "base_url":     suite.base_url,
            "timestamp":    suite.timestamp,
            "duration_ms":  suite.duration_ms,
            "total":        suite.total,
            "passed":       suite.passed,
            "failed":       suite.failed,
            "errors":       suite.errors,
            "pass_rate":    suite.pass_rate,
            "avg_latency_ms": suite.avg_latency_ms,
        },
        "results": [
            {
                "id":     r.endpoint_id,
                "name":   r.endpoint_name,
                "method": r.method,
                "url":    r.url,
                "passed": r.passed,
                "tags":   r.tags,
                "error":  r.error,
                "checks": {
                    "status": {
                        "passed":   r.status.passed   if r.status   else None,
                        "expected": r.status.expected_status if r.status else None,
                        "actual":   r.status.actual_status   if r.status else None,
                    } if r.status else None,
                    "latency": {
                        "passed":      r.latency.passed      if r.latency else None,
                        "latency_ms":  r.latency.latency_ms  if r.latency else None,
                        "threshold_ms":r.latency.threshold_ms if r.latency else None,
                        "tier":        r.latency.tier         if r.latency else None,
                    } if r.latency else None,
                    "schema": {
                        "passed": r.schema.passed if r.schema else None,
                        "errors": r.schema.errors if r.schema else [],
                    } if r.schema else None,
                    "payload": {
                        "passed":      r.payload.passed           if r.payload else None,
                        "size_bytes":  r.payload.payload_size_bytes if r.payload else None,
                        "issues":      r.payload.issues            if r.payload else [],
                    } if r.payload else None,
                }
            }
            for r in suite.results
        ]
    }
